export const details = [
  {
    city: "sdklfj",
    communicationAddress: "kjsdklfj",
    country: "India",
    dob: "2020-07-10",
    emailId: "ksdjf@m.com",
    firstName: "arvind",
    gender: "female",
    id: 1,
    isChecked: false,
    lastName: "suriya",
    mobileNumber: "-1",
    name: "arvind suriya",
    orgName: "VhiTech",
    permanentAddress: "jksdjklf",
    pincode: "09876",
    state: "TamilNadu",
  },
  {
    city: "kjsdklf,",
    communicationAddress: "kljsdklfkl",
    country: "India",
    dob: "2020-07-17",
    emailId: "sdkffj@gm.com",
    firstName: "aditya",
    gender: "male",
    id: 2,
    isChecked: false,
    lastName: "suriya",
    mobileNumber: "0987654",
    name: "aditya suriya",
    orgName: "VhiTech",
    permanentAddress: "jklsdjfklj",
    pincode: "09876",
    state: "TamilNadu",
  },
  {
    city: "kjsdklf,",
    communicationAddress: "kljsdklfkl",
    country: "India",
    dob: "2020-07-17",
    emailId: "sdkffj@gm.com",
    firstName: "kesav",
    gender: "male",
    id: 3,
    isChecked: false,
    lastName: "murali",
    mobileNumber: "0987654",
    name: "kesav murali",
    orgName: "VhiTech",
    permanentAddress: "jklsdjfklj",
    pincode: "09876",
    state: "TamilNadu",
  },
  {
    city: "kjsdklf,",
    communicationAddress: "kljsdklfkl",
    country: "India",
    dob: "2020-07-17",
    emailId: "sdkffj@gm.com",
    firstName: "dave",
    gender: "female",
    id: 4,
    isChecked: false,
    lastName: "jon",
    mobileNumber: "0987654",
    name: "dave jon",
    orgName: "VhiTech",
    permanentAddress: "jklsdjfklj",
    pincode: "09876",
    state: "TamilNadu",
  },
  {
    city: "kjsdklf,",
    communicationAddress: "kljsdklfkl",
    country: "India",
    dob: "2020-07-17",
    emailId: "sdkffj@gm.com",
    firstName: "bill",
    gender: "female",
    id: 5,
    isChecked: false,
    lastName: "yard",
    mobileNumber: "0987654",
    name: "bill yard",
    orgName: "VhiTech",
    permanentAddress: "jklsdjfklj",
    pincode: "09876",
    state: "TamilNadu",
  },
];

export default details